markdown: kramdown
highlighter: null
permalink: /:year/:month/:day/:title/
#url: https://www.gombaszog.sk/
timezone: Europe/Bratislava
exclude: [ 'README.md', 'LICENSE', 'Gemfile', 'Makefile', '_deprecated', '_compress_images_cache.yml']
include: ['.htaccess']
excerpt_separator: <!--more-->
minify_html: true
plugins: 
  - jekyll-assets
  - jekyll-minify-html
  - jekyll-multiple-languages-plugin
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 8"
  cache_type: memory
  prefix: "/assets"
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/downloads
  compress:
    css: true
    js: true
  js_compressor:  uglifier
  css_compressor: sass
defaultLang: hu
baseurl: ""
#languages: ["hu", "en", "sk"]
languages: ["hu"]
exclude_from_localizations: ["_assets", "_posts", "_plugins", "_layouts", "_includes", "_deprecated"]
#languageNames:
  #hu: Magyar
  #en: English
  #sk: Slovenčina
  

